import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono, Orbitron, Inter } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "../components/navbar";
import TransitionFunc from "../transition/transition";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const AkiraExpanded = localFont({
  src: "../public/fonts/AkiraExpanded.woff2",
  variable: "--font-akira",
});

export const metadata: Metadata = {
  title: "F1 2020",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${AkiraExpanded.variable} ${orbitron.variable} ${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col overflow-y-scroll no-scrollbar">
        <Navbar />
        <TransitionFunc>{children}</TransitionFunc>
      </body>
    </html>
  );
}
